name: Build library (kotlin, python)

on:
  workflow_dispatch:

jobs:
    build:
        name: Build bindings
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                ref: main
            - name: Install rust
              run: |
                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            - name: Cache rust modules
              id: cache-rust
              uses: actions/cache@v3
              env:
                cache-name: cache-rust-modules
              with:
                # npm cache files are stored in `~/.npm` on Linux/macOS
                path: target
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: |
                  ${{ runner.os }}-build-${{ env.cache-name }}-
                  ${{ runner.os }}-build-
                  ${{ runner.os }}-
              
            - name: Build kotlin bindings
              run: |
                bash kotlin-build.sh
            
            - name: Save kotlin artifact
              uses: actions/upload-artifact@v4
              with:
                name: kotlin-bindings
                path: |
                  bindings/kotlin

            - name: Build python bindings
              run: |
                bash python-build.sh

            - name: Save python artifact
              uses: actions/upload-artifact@v4
              with:
                name: pythons-bindings
                path: |
                  bindings/python